---
title: "Exploring the HopFoehnTemp Data"
author: "Tino Schneidewind"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list= ls())
library(dplyr); library(ggplot2) ; library(lubridate); library(patchwork)
library(tidyr) ; library(tidyverse);  library(plotly); library(hrbrthemes)
library(viridis); library(forcats)

# notes for creating html document, paste this into Console
# rmarkdown::render("C:/Users/tinos/Documents/Master - Climate Science/3 - Master Thesis/master_thesis/vignettes/region_selection.Rmd", output_format = "html_document")
```

Lets explore the data, and some descriptive statistics, its distribution, the time series etc. I will start of with **only the station Altdorf** as a placeholder for all individual stations. Afterwards, I will look into the **buffer aggregated** data.

```{r, data}
# read Altdorf data with 5k buffer radius
altdorf = read.csv("C:/Users/tinos/Documents/Master - Climate Science/3 - Master Thesis/master_thesis/data/MedStat_aggregated/by_station/Altdorf_buffer_5000.csv")

# convert date to date format
altdorf$date <- as.Date(altdorf$date)

str(altdorf)
summary(altdorf)

```

```{r density, echo=FALSE}
# investigate the distribution of all variables using histograms 
altdorf_long <- altdorf[4:15] %>%
  pivot_longer(cols = everything(), names_to = "variable", values_to = "value")

ggplot(altdorf_long, aes(x = value)) +
  geom_histogram(bins = 20, fill = "blue", color = "black") +
  facet_wrap(~ variable, scales = "free_x") +  # Create separate histogram for each variable
  theme_minimal() +
  labs(title = "Histograms of All Variables", x = "Values", y = "Frequency")

altdorf_monthly <- altdorf %>%
  mutate(year_month = floor_date(date, "month")) %>%
  group_by(year_month) %>%
  summarise(across(c(all : uri), sum))

altdorf_monthly_long <- altdorf_monthly[2:14] %>%
  pivot_longer(cols = everything(), names_to = "variable", values_to = "value")
  
ggplot(altdorf_monthly_long, aes(x = value)) +
  geom_histogram(bins = 20, fill = "blue", color = "black") +
  facet_wrap(~ variable, scales = "free_x") +  # Create separate histogram for each variable
  theme_minimal() +
  labs(title = "Histograms of Monthly Sums of Variables", x = "Values", y = "Frequency")

```


```{r time}
# time series of monthly hospitalizations

```

```{r corr}
# correlation matrix
data = read.csv("C:/Users/tinos/Documents/Master - Climate Science/3 - Master Thesis/master_thesis/data/MedStat_aggregated/hosp_buffer_5000.csv")

ggplot(altdorf, aes(x = as.factor(all))) +
  geom_bar(fill = "lightgreen", color = "black") +
  theme_minimal() +
  labs(x = "Integer Values", y = "Frequency")
```

```{r bubble}
# bubble plot of temperature and foehn index
```

```{r}
# heatmap
library(corrplot)
corr_matrix <- cor(altdorf[sapply(altdorf, is.numeric)], use = "complete.obs")
corrplot(corr_matrix, method = "color")
```

