---
title: "Model"
author: "Tino Schneidewind"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

#### This documents serves to determine adequat modeling paramteters for my Distributed Lagged (Non-Linear) Model DLNM.

```{r packages, message=FALSE, warning=FALSE}
library(viridisLite); library(dlnm); library(splines); library(ggplot2); library(viridis)
```
```{r data, message=FALSE, warning=FALSE}
# data
data = read.csv("C:/Users/tinos/Documents/Master - Climate Science/3 - Master Thesis/master_thesis/data/MedStat_aggregated/hosp_buffer_5000.csv")

# we add an Month and Year Index to the data
data$date = as.Date(data$date)
data$Year = as.numeric(format(data$date, "%Y")); data$month = as.numeric(format(data$date, "%m"))

# exclude rows with NA
data <- na.exclude(data)
```

To reduce processing speed, the data will be shortened. I want to keep all 8 stations and 2 years of the time series of each station in the analysis. 

```{r data shortening}
# save the first station in the shortened data set for later
data_short <- data[1:730,]
# extract all station names but the first
station_names <- unique(data$station)

# extract 4 years of every station and save it in data_shot
for(i in station_names[-1]){
  x <- data[data$station == i,]
  # print(length(unique(x$Year[1:1461])))
  data_short <- rbind(data_short, x[1:730,])
}
```
```{r plot basic timeseries of hospitalizations, echo=FALSE}
par(mfrow=c(2,2))
for (i in c(1,2,5,8)) {
plot(data_short$date[data_short$station == station_names[i]], 
     data_short$all[data_short$station == station_names[i]], 
     col = 1, 
     xlab = "Date", 
     ylab = "Daily hospitalisations", 
     cex = 1, pch = "째", ylim = c(0,18),
     main = station_names[i])
}

```


```{r plot basic timeseries of foehn, echo=FALSE}
par(mfrow=c(2,2))
for (i in c(1,2,5,8)) {
plot(data_short$date[data_short$station == station_names[i]], 
     data_short$f_id[data_short$station == station_names[i]], 
     col = 3, 
     xlab = "Date", 
     ylab = "Daily foehn score", 
     cex = 1, pch = "째", ylim = c(0,288),
     main = station_names[i])
}
```

```{r plot basic timeseries of temperature, echo=FALSE}
par(mfrow=c(2,2))
for (i in c(1,2,5,8)) {
plot(data_short$date[data_short$station == station_names[i]], 
     data_short$temp[data_short$station == station_names[i]], 
     col = 2, 
     xlab = "Date", 
     ylab = "Daily mean temperature", 
     cex = 1, pch = "째", ylim = c(-20,30),
     main = station_names[i])
}

```

```{r temperature plot, echo=FALSE}
plot(data_short$temp,
     col = 2,
     ylab = "Daily mean temperature",
     xlab = "Index across all dates",
     cex = 1, pch = "째", ylim = c(-20,30),
     main = "Temperature Series"
     )

```

